{% set name = "scikit-survival" %}
{% set version = "0.21.0" %}
{% set sha256 = "adc744b65983dced8142ec31465389fc738405d589051251e5447aad9a1e02bc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: {{ PYTHON }} -m pip install -vvv .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - packaging
    - setuptools_scm
    - cython >=0.29.16,<3.0
    - numpy
    - scikit-learn >=1.2.0,<1.3

  run:
    - python
    - ecos
    - numexpr
    - {{ pin_compatible('numpy') }}
    - importlib-resources >=1.3  # [py38]
    - joblib
    - osqp !=0.6.0,!=0.6.1
    - pandas >=1.0.5
    - scikit-learn >=1.2.0,<1.3
    - scipy >=1.3.2
    - setuptools

test:
  # Python imports
  imports:
    - sksurv
    - sksurv.base
    - sksurv.bintrees
    - sksurv.column
    - sksurv.compare
    - sksurv.datasets
    - sksurv.ensemble
    - sksurv.ensemble.boosting
    - sksurv.ensemble.forest
    - sksurv.ensemble.survival_loss
    - sksurv.exceptions
    - sksurv.functions
    - sksurv.io
    - sksurv.io.arffread
    - sksurv.io.arffwrite
    - sksurv.kernels
    - sksurv.kernels.clinical
    - sksurv.linear_model
    - sksurv.linear_model.aft
    - sksurv.linear_model.coxnet
    - sksurv.linear_model.coxph
    - sksurv.metrics
    - sksurv.meta
    - sksurv.meta.base
    - sksurv.meta.ensemble_selection
    - sksurv.meta.stacking
    - sksurv.nonparametric
    - sksurv.preprocessing
    - sksurv.svm
    - sksurv.svm.minlip
    - sksurv.svm.naive_survival_svm
    - sksurv.svm.survival_svm
    - sksurv.testing
    - sksurv.tree
    - sksurv.tree.tree
    - sksurv.util
  source_files:
    - tests/*
  requires:
    - pytest >=5.4.0
  commands:
    - pytest --fixtures .
    - pytest -m "not slow"  # [linux]

about:
  home: https://github.com/sebp/scikit-survival
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Survival analysis built on top of scikit-learn'
  doc_url: https://scikit-survival.readthedocs.io/en/latest/
  dev_url: https://github.com/sebp/scikit-survival

extra:
  recipe-maintainers:
    - sebp
