{% set name = "scikit-survival" %}
{% set version = "0.8" %}
{% set sha256 = "456983190a1054615e2efd5e7aeeec4a06da009c94d71ebe6f6f769b30c87c6f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - setuptools_scm
    - cython >=0.29
    - numpy

  run:
    - python
    - cvxopt >=1.2
    - cvxpy >=1.0
    - numexpr
    - {{ pin_compatible('numpy') }}
    - pandas >=0.19.0,<0.24
    - scikit-learn >=0.19.0,<0.21
    - scipy >=0.16,<1.3.0
    - setuptools

test:
  # Python imports
  imports:
    - sksurv
    - sksurv.base
    - sksurv.bintrees
    - sksurv.column
    - sksurv.datasets
    - sksurv.ensemble
    - sksurv.ensemble.boosting
    - sksurv.ensemble.survival_loss
    - sksurv.io
    - sksurv.io.arffread
    - sksurv.io.arffwrite
    - sksurv.kernels
    - sksurv.kernels.clinical
    - sksurv.linear_model
    - sksurv.linear_model.aft
    - sksurv.linear_model.coxph
    - sksurv.metrics
    - sksurv.meta
    - sksurv.meta.base
    - sksurv.meta.ensemble_selection
    - sksurv.meta.stacking
    - sksurv.preprocessing
    - sksurv.svm
    - sksurv.svm.minlip
    - sksurv.svm.naive_survival_svm
    - sksurv.svm.survival_svm
    - sksurv.util
  source_files:
    - tests/*
  requires:
    - pytest
  commands:
    - python -m pytest -m "not slow"  # [not osx]

about:
  home: https://github.com/sebp/scikit-survival
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Survival analysis built on top of scikit-learn'
  doc_url: https://scikit-survival.readthedocs.io/en/latest/
  dev_url: https://github.com/sebp/scikit-survival

extra:
  recipe-maintainers:
    - sebp
