# The language in this case has no bearing - we are going to be making use of conda.
language: generic

os: osx

# Set BINSTAR_TOKEN
env:
    matrix:
        - CONFIG=osx_py36
        - CONFIG=osx_py37
    global:
         secure: "H64pb6GTd1Y2SLpXrnYrk5GKgA+1n15GNBp+0Lku7SBtG8TQxJx46REUjTlodyomAZX1jqdc5gmoGkmfnOtC/7EOJfFvM762miAXmxvqEwkZIfwoFgJVdKowRxItAqXp3Yxr5FrUS8vjFevuCoHzvXrxL5lc15wmqoY8PQw1moCJDwUPIP4wiAHgMohpTs6zwyc3No11lEVtSBGwMnHm3rljR8Kfx/pwpOn6WPxuGEoBZTuz1kA9PhBe1YUUoqLcCLft/SCCo1NKemu11LAZLyPJOwoCoIey6tmS4e4xMw0RqrE/Cz2fBsRgcJyVImPkW40AyL7DZ3aeoj02QX358kGhPMWTawNwYZqNI2HA/b4jwlVu7ksRHrDzcEn8+Wm3V49ngY7xHdgHlkmlL2IGaWpKRKhQvOchU59fnFJPtpkJCi/gQmDQv3ZJtIP1+qXodkC0tdsbxqRifqU6ZtColB8NkSxKMo9fpn4AcUqjCG+1Ux+hPaqYLmKx28zA8A6A1pE/II1RoumY+uvm3AlDvp18agLhnMYON6FkT50wzgPU6+KLWqfKZbom+qBpzm13EZ6nOWoQEZx043EQ2dVWwqH+zfLp94WdAPHqGaD7jTp038w1wyNdzUNpczE4VO1l9sP8y5AQM3J3b2fIgV2gfmLMErxW1R4WVN3abRVMVzI="

before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew

install:
    # Install Miniconda.
    - find /Applications/Xcode.app -name stdio.h
    - ls Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
    - ./install_miniconda.sh

script:
    - source ~/miniconda/bin/activate base
    - conda build -m build_config/${CONFIG}.yaml ./recipe
    # from https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/upload_or_check_non_existence.py
    - ./upload_or_check_non_existence -m build_config/${CONFIG}.yaml ./recipe sebp --channel=main
