# The language in this case has no bearing - we are going to be making use of conda.
language: generic

# Set BINSTAR_TOKEN
env:
    global:
         secure: RecwfhyYe+/IzFeM29a8Dda1Bc5rDnldjqkssItN9ndNxBLQ1I1kYlxrPwBEuBdPSucUjF6AUh0StkYtsKXY6B2BzhBuIQLcmhY/usAJQftnEltGGmijVA4c+b/uMwB2IRi9RXm5tvFLwHCFv2cgr/mPuJXTALp69Nob9+dEP0XqSJUoxH0LrGwjiITiEmCugVrRl4rnJWkUXchvtnhnnsvPAokNZ0rUn4FI5w805AoUv935MllqUVp+rWLeN8sEzUpzoYKmU62Q0oQYJZVn0XNGErV8qnS1SGVWdtE1PHUR0uZsiLYmQWJjCOSv/aqh+W6lkx9buqtSgKdQOtqtaYWlYZ010SvIciex7Ykj6UROX/ZRACWqQurxGMlZsFG5b6ClPfQK01jp53iwjfNiizZjFLZbAIfJKy8wX1AkoZT1Bjhflvcf5ku3veVoTfp3ggf92L+eqwHUW/sZ8izuyG2Hw0VyWnj/q00tq4wl3GDSfHR0ipCkghKk6qXZ7oTqJKHlxHXoesyky85QqgBLGFxeLlDT/JbawoN8YTN+4oErHWUk7ubpHbOrzCwBvxzISPNKR/BKd1JsfN/AGZDyAahyfDnF/RLPD4elGi1w6kYUNGj1QlvzfFFTwcBU6hLqoQzrG9FNh8kQMr+MLtVyHm/3iZfYP2tvjrn6bG8iwDg=

install:
    # Install Miniconda.
    - ./install_miniconda.sh

script:
    - source ~/miniconda/bin/activate root
    - conda build ./recipe
    # from https://github.com/conda-forge/conda-forge-build-setup-feedstock/blob/master/recipe/upload_or_check_non_existence.py
    - ./upload_or_check_non_existence ./recipe sebp --channel=main
